server:
  port: 8082

welcome:
  message: Welcome to my Department system!

spring:
  profiles:
    active: qa


---

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/dcbapp
    username: root
    password: 1q2w3e
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    activate:
      on-profile: dev


---

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/dcbapp-qa
    username: root
    password: 1q2w3e
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    activate:
      on-profile: qa

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env, beans"

---

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/dcbapp-prod
    username: root
    password: 1q2w3e
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    activate:
      on-profile: prod
